version: "2.1"

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  product-composite-service:
    build:
      context: ./product-composite-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      product-service:
        condition: service_started
      review-service:
        condition: service_started
      recommendation-service:
        condition: service_started

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      mysql:
        condition: service_started

  recommendation-service:
    build:
      context: ./recommendation-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      mysql:
        condition: service_started

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      mysql:
        condition: service_started

volumes:
  mysql_data:
    external: true

